/** @type {import('tailwindcss').Config} */
const v = (name) => `rgb(var(--${name}) / <alpha-value>)`;

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": v("background"),
        "surface": v("surface"),
        "surface-dim": v("background"),
        "surface-bright": v("surface-container-highest"),
        "surface-tint": v("primary"),
        "surface-variant": v("surface-container-highest"),
        "surface-container-lowest": v("background"),
        "surface-container-low": v("surface-container-low"),
        "surface-container": v("surface-container"),
        "surface-container-high": v("surface-container-high"),
        "surface-container-highest": v("surface-container-highest"),
        "on-surface": v("on-surface"),
        "on-background": v("on-surface"),
        "on-surface-variant": v("on-surface-variant"),
        "outline": v("outline"),
        "outline-variant": v("outline-variant"),
        "primary": v("primary"),
        "primary-container": v("primary"),
        "primary-dim": v("primary"),
        "primary-fixed": v("primary"),
        "primary-fixed-dim": v("primary"),
        "inverse-primary": v("primary"),
        "on-primary": v("on-primary"),
        "on-primary-container": v("on-primary"),
        "on-primary-fixed": v("on-primary"),
        "on-primary-fixed-variant": v("on-primary"),
        "secondary": v("secondary"),
        "secondary-dim": v("secondary"),
        "secondary-fixed": v("secondary"),
        "secondary-fixed-dim": v("secondary"),
        "secondary-container": "#00687a",
        "on-secondary": "#004b58",
        "on-secondary-container": "#ecfaff",
        "on-secondary-fixed": "#003a45",
        "on-secondary-fixed-variant": "#005969",
        "tertiary": v("tertiary"),
        "tertiary-dim": v("tertiary"),
        "tertiary-fixed": v("tertiary"),
        "tertiary-fixed-dim": v("tertiary"),
        "tertiary-container": v("tertiary"),
        "on-tertiary": "#3d0047",
        "on-tertiary-container": "#19001e",
        "on-tertiary-fixed": "#300038",
        "on-tertiary-fixed-variant": "#660075",
        "error": v("error"),
        "error-dim": v("error"),
        "error-container": "#a70138",
        "on-error": "#490013",
        "on-error-container": "#ffb2b9",
        "inverse-surface": "#fcf8ff",
        "inverse-on-surface": "#55545b",
        "accent": "rgb(var(--accent, var(--primary)) / <alpha-value>)",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "body": ["Manrope", "system-ui", "sans-serif"],
        "label": ["Manrope", "system-ui", "sans-serif"],
      },
      boxShadow: {
        "card": "0 4px 16px rgb(0 0 0 / 0.25)",
        "elevated": "0 12px 32px rgb(0 0 0 / 0.45)",
        "overlay": "0 24px 64px rgb(0 0 0 / 0.6)",
      },
      transitionTimingFunction: {
        "out-expo": "cubic-bezier(0.16, 1, 0.3, 1)",
      },
      keyframes: {
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "scale-in": { from: { opacity: "0", transform: "scale(0.96)" }, to: { opacity: "1", transform: "scale(1)" } },
        "sheet-up": { from: { transform: "translateY(100%)" }, to: { transform: "translateY(0)" } },
        "toast-in": { from: { opacity: "0", transform: "translateY(12px) scale(0.98)" }, to: { opacity: "1", transform: "translateY(0) scale(1)" } },
        "shimmer": { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
      },
      animation: {
        "fade-in": "fade-in 180ms ease-out",
        "scale-in": "scale-in 180ms cubic-bezier(0.16, 1, 0.3, 1)",
        "sheet-up": "sheet-up 240ms cubic-bezier(0.16, 1, 0.3, 1)",
        "toast-in": "toast-in 220ms cubic-bezier(0.16, 1, 0.3, 1)",
        "shimmer": "shimmer 1.6s linear infinite",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    function ({ addVariant }) {
      addVariant('can-hover', '@media (hover: hover) and (pointer: fine)');
      addVariant('touch', '@media (hover: none), (pointer: coarse)');
    },
  ],
};
